import {
  IconAlertTriangle,
  IconArmchair,
  IconArrowLeft,
  IconArrowRight,
  IconBell,
  IconBook,
  IconBrandGoogleDrive,
  IconBrandInstagram,
  IconBrandPinterest,
  IconBrandSlack,
  IconBrandTwitter,
  IconCalendar,
  IconCheck,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircleCheck,
  IconCircleX,
  IconCopy,
  IconCurrencyDollar,
  IconDotsVertical,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFilter,
  IconHeart,
  IconHome,
  IconInbox,
  IconInfoCircle,
  IconList,
  IconLoader2,
  IconLogout,
  IconMail,
  IconMapPin,
  IconMenu2,
  IconMessage,
  IconMessageCircle,
  IconMessages,
  IconMinus,
  IconMoon,
  IconPhone,
  IconPlus,
  type IconProps,
  IconReceiptRupee,
  IconRefresh,
  IconSearch,
  IconSend,
  IconSettings,
  IconShieldCheck,
  IconShoppingBag,
  IconStar,
  IconSun,
  IconTool,
  IconTrash,
  IconUpload,
  IconUser,
  IconUsers,
  IconX,
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  // Navigation
  home: IconHome,
  calendar: IconCalendar,
  users: IconUsers,
  settings: IconSettings,
  whatsapp: IconMessageCircle,
  analytics: IconArmchair,
  knowledgeBase: IconBook,
  services: IconTool,
  notifications: IconBell,
  sun: IconSun,
  moon: IconMoon,
  messages: IconMessages,
  billing: IconReceiptRupee,
  shieldCheck: IconShieldCheck,

  // Actions
  logout: IconLogout,
  menu: IconMenu2,
  close: IconX,
  search: IconSearch,
  add: IconPlus,
  edit: IconEdit,
  delete: IconTrash,
  check: IconCheck,
  checkCheck: IconChecks,
  eye: IconEye,
  eyeOff: IconEyeOff,
  upload: IconUpload,
  download: IconDownload,
  refresh: IconRefresh,
  filter: IconFilter,
  copy: IconCopy,
  externalLink: IconExternalLink,
  send: IconSend,
  list: IconList,
  heart: IconHeart,
  shoppingBag: IconShoppingBag,
  star: IconStar,
  minus: IconMinus,

  // Navigation arrows
  chevronDown: IconChevronDown,
  chevronUp: IconChevronUp,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  arrowLeft: IconArrowLeft,
  arrowRight: IconArrowRight,

  // Contact
  phone: IconPhone,
  mail: IconMail,
  googleDrive: IconBrandGoogleDrive,
  slack: IconBrandSlack,
  instagram: IconBrandInstagram,
  twitter: IconBrandTwitter,
  pinterest: IconBrandPinterest,

  // UI / Feedback
  spinner: IconLoader2,
  warning: IconAlertTriangle,
  info: IconInfoCircle,
  inbox: IconInbox,
  dotsVertical: IconDotsVertical,
  circleCheck: IconCircleCheck,
  circleX: IconCircleX,

  user: IconUser,
  mapPin: IconMapPin,
  currencyDollar: IconCurrencyDollar,
  message: IconMessage,
  plus: IconPlus,
  trash: IconTrash,
} as const;

export type IconName = keyof typeof Icons;
